name: E2E Testing via Playwright
on:
 push:
  branches: [main, master]
 pull_request:
  branches: [main, master]
jobs:
 test:
  timeout-minutes: 60
  runs-on: ubuntu-latest
  steps:
   - name: Wait for Vercel preview deployment to be ready
     uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
     id: waitForVercelPreviewDeployment
     with:
      token: ${{ secrets.GITHUB_TOKEN }}
      max_timeout: 600
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
     with:
      node-version: 18
   - name: Setup pnpm 
     uses: pnpm/action-setup@v2.4.0
     with:
          version: 8
   - name: Install dependencies
     run: pnpm install
   - name: Install Playwright Browsers
     run: pnpm exec playwright install --with-deps
   - name: Run Playwright tests
     run: pnpm exec playwright test
     env:
       PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitForDeploy.outputs.url }}

   - uses: actions/upload-artifact@v3
     if: always()
     with:
      name: playwright-report
      path: playwright-report/
      retention-days: 30
